version: '3.7'
services:
  redis:
      image: redis:latest
      ports:
        - "6379:6379"

  redis_insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis

  postgres:
      image: postgres:11
      env_file:
        - .env
      ports:
        - "5432:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U airflow" ]
        interval: 10s
        timeout: 5s
        retries: 5

  airflow-webserver:
        build: .
        restart: always
        command: webserver
        depends_on:
          postgres:
            condition: service_healthy
        ports:
          - "8080:8080"
        env_file:
          - .env
        healthcheck:
          test: [ "CMD-SHELL", "[ -f /airflow/airflow-webserver.pid ]" ]
          interval: 30s
          timeout: 30s
          retries: 3
        volumes:
          - ./dags:/opt/airflow/dags

  airflow-worker-1:
        build: .
        command: worker
        restart: always
        depends_on:
          - airflow-webserver
        ports:
          - "8081:8080"
        env_file:
          - .env
        environment:
          - QUEUE_NAME=queue_1

  airflow-worker-2:
        build: .
        command: worker
        restart: always
        depends_on:
          - airflow-webserver
        ports:
          - "8082:8080"
        env_file:
          - .env
        environment:
          - QUEUE_NAME=queue_2

  airflow-flower:
        build: .
        command: flower
        restart: always
        depends_on:
          - airflow-worker-1
          - airflow-worker-2
        ports:
          - "5555:5555"
        env_file:
          - .env